spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///springboot_web_demo?charactEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    servlet:
      multipart:
        enabled: true
        max-file-size: 2000MB
        max-request-size: 2000MB
  resources:
    # 静态资源配置
    static-locations: classpath:/templates/, classpath:/static/
  thymeleaf:
    cache: false  # 关闭模板引擎缓存
  messages:
    basename: i18n.login  # 配置国际化基础名(包名.基础名)
  mvc:
    date-format: yyyy-MM-dd   # 配置日期转换类型
    hiddenmethod:
      filter:
        enabled: true    # 开启隐藏域的 method
server:
  port: 8080  # 服务器地址

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启mp日志



